# Generated by Django 4.2.7 on 2025-09-13 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JenisLaporan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nama_laporan", models.CharField(max_length=100)),
                ("kode_laporan", models.CharField(max_length=20, unique=True)),
                ("deskripsi", models.TextField(blank=True)),
                ("template_laporan", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Jenis Laporan",
                "verbose_name_plural": "Jenis Laporan",
                "ordering": ["nama_laporan"],
            },
        ),
        migrations.CreateModel(
            name="TemplateLaporan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nama_template", models.CharField(max_length=100)),
                ("konten_template", models.TextField()),
                (
                    "variabel_template",
                    models.JSONField(
                        default=list,
                        help_text="Daftar variabel yang bisa digunakan dalam template",
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "jenis_laporan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="laporan.jenislaporan",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Template Laporan",
                "verbose_name_plural": "Template Laporan",
            },
        ),
        migrations.CreateModel(
            name="Laporan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("judul_laporan", models.CharField(max_length=200)),
                ("periode_awal", models.DateField()),
                ("periode_akhir", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Menunggu Review"),
                            ("approved", "Disetujui"),
                            ("rejected", "Ditolak"),
                            ("published", "Dipublikasikan"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("konten_laporan", models.TextField()),
                (
                    "file_laporan",
                    models.FileField(blank=True, null=True, upload_to="laporan/files/"),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_reason", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="laporan_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "jenis_laporan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="laporan.jenislaporan",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Laporan",
                "verbose_name_plural": "Laporan",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExportLaporan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "format_file",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("excel", "Excel"),
                            ("csv", "CSV"),
                            ("word", "Word"),
                        ],
                        max_length=10,
                    ),
                ),
                ("file_export", models.FileField(upload_to="laporan/export/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="processing",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "laporan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="laporan.laporan",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Export Laporan",
                "verbose_name_plural": "Export Laporan",
            },
        ),
    ]
