# Generated by Django 4.2.7 on 2025-09-13 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Penduduk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "nik",
                    models.CharField(max_length=16, unique=True, verbose_name="NIK"),
                ),
                ("nama_lengkap", models.CharField(max_length=100)),
                (
                    "jenis_kelamin",
                    models.CharField(
                        choices=[("L", "Laki-laki"), ("P", "Perempuan")], max_length=1
                    ),
                ),
                ("tempat_lahir", models.CharField(max_length=100)),
                ("tanggal_lahir", models.DateField()),
                (
                    "agama",
                    models.CharField(
                        choices=[
                            ("islam", "Islam"),
                            ("kristen", "Kristen"),
                            ("katolik", "Katolik"),
                            ("hindu", "Hindu"),
                            ("buddha", "Buddha"),
                            ("khonghucu", "Khonghucu"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status_kawin",
                    models.CharField(
                        choices=[
                            ("belum_kawin", "Belum Kawin"),
                            ("kawin", "Kawin"),
                            ("cerai_hidup", "Cerai Hidup"),
                            ("cerai_mati", "Cerai Mati"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "pendidikan",
                    models.CharField(
                        choices=[
                            ("tidak_sekolah", "Tidak Sekolah"),
                            ("tidak_tamat_sd", "Tidak Tamat SD"),
                            ("tamat_sd", "Tamat SD"),
                            ("tamat_smp", "Tamat SMP"),
                            ("tamat_sma", "Tamat SMA"),
                            ("tamat_diploma", "Tamat Diploma"),
                            ("tamat_sarjana", "Tamat Sarjana"),
                            ("tamat_pascasarjana", "Tamat Pascasarjana"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "pekerjaan",
                    models.CharField(
                        choices=[
                            ("tidak_bekerja", "Tidak Bekerja"),
                            ("pelajar", "Pelajar"),
                            ("mahasiswa", "Mahasiswa"),
                            ("pns", "PNS"),
                            ("tni", "TNI"),
                            ("polri", "Polri"),
                            ("karyawan_swasta", "Karyawan Swasta"),
                            ("wiraswasta", "Wiraswasta"),
                            ("petani", "Petani"),
                            ("nelayan", "Nelayan"),
                            ("buruh", "Buruh"),
                            ("pensiunan", "Pensiunan"),
                            ("lainnya", "Lainnya"),
                        ],
                        max_length=30,
                    ),
                ),
                ("alamat", models.TextField()),
                ("rt", models.CharField(max_length=3)),
                ("rw", models.CharField(max_length=3)),
                ("dusun", models.CharField(max_length=100)),
                ("nama_ayah", models.CharField(blank=True, max_length=100)),
                ("nama_ibu", models.CharField(blank=True, max_length=100)),
                ("nama_pasangan", models.CharField(blank=True, max_length=100)),
                ("no_telepon", models.CharField(blank=True, max_length=15)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "foto",
                    models.ImageField(
                        blank=True, null=True, upload_to="penduduk/foto/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("keterangan", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Penduduk",
                "verbose_name_plural": "Data Penduduk",
                "ordering": ["nama_lengkap"],
            },
        ),
        migrations.CreateModel(
            name="Keluarga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "nomor_kk",
                    models.CharField(
                        max_length=16, unique=True, verbose_name="Nomor KK"
                    ),
                ),
                ("alamat", models.TextField()),
                ("rt", models.CharField(max_length=3)),
                ("rw", models.CharField(max_length=3)),
                ("dusun", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "kepala_keluarga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kepala_keluarga",
                        to="penduduk.penduduk",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Keluarga",
                "verbose_name_plural": "Data Keluarga",
                "ordering": ["nomor_kk"],
            },
        ),
        migrations.CreateModel(
            name="AnggotaKeluarga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status_hubungan",
                    models.CharField(
                        choices=[
                            ("kepala_keluarga", "Kepala Keluarga"),
                            ("istri", "Istri"),
                            ("anak", "Anak"),
                            ("menantu", "Menantu"),
                            ("cucu", "Cucu"),
                            ("orang_tua", "Orang Tua"),
                            ("mertua", "Mertua"),
                            ("famili_lain", "Famili Lain"),
                            ("pembantu", "Pembantu"),
                            ("lainnya", "Lainnya"),
                        ],
                        max_length=30,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "keluarga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anggota",
                        to="penduduk.keluarga",
                    ),
                ),
                (
                    "penduduk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="penduduk.penduduk",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Anggota Keluarga",
                "verbose_name_plural": "Anggota Keluarga",
                "unique_together": {("keluarga", "penduduk")},
            },
        ),
    ]
